pipeline:
  name: remoteISTest
  identifier: remoteISTest
  tags: {}
  projectIdentifier: releasemanagement
  orgIdentifier: ReleaseManagement
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
              - step:
                  type: Wait
                  name: Wait_2
                  identifier: Wait_2
                  spec:
                    duration: 10m
        tags: {}
  variables:
    - name: var1
      type: String
      description: ""
      required: false
      value: <+input>
